---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - tg.azamaton.ru
  resources:
  - contactpoints
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - tg.azamaton.ru
  resources:
  - contactpoints/finalizers
  verbs:
  - update
- apiGroups:
  - tg.azamaton.ru
  resources:
  - contactpoints/status
  verbs:
  - get
  - patch
  - update
