---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  - services
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - services/status
  verbs:
  - get
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps
  resources:
  - deployments/status
  verbs:
  - get
- apiGroups:
  - tg.azamaton.ru
  resources:
  - contactpoints
  - trackedfields
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - tg.azamaton.ru
  resources:
  - contactpoints/finalizers
  - trackedfields/finalizers
  verbs:
  - update
- apiGroups:
  - tg.azamaton.ru
  resources:
  - contactpoints/status
  - trackedfields/status
  verbs:
  - get
  - patch
  - update
