apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: habr-k8s-resource-tracker
    app.kubernetes.io/managed-by: kustomize
  name: controller-manager
  namespace: system
