# permissions for end users to view trackedfields.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: habr-k8s-resource-tracker
    app.kubernetes.io/managed-by: kustomize
  name: trackedfield-viewer-role
rules:
- apiGroups:
  - tg.azamaton.ru
  resources:
  - trackedfields
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - tg.azamaton.ru
  resources:
  - trackedfields/status
  verbs:
  - get
