apiVersion: tg.azamaton.ru/v1
kind: ContactPoint
metadata:
  labels:
    app.kubernetes.io/name: habr-k8s-resource-tracker
    app.kubernetes.io/managed-by: kustomize
  name: contactpoint-sample
spec:
  # TODO(user): Add fields here
